# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1160, 880)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMouseTracking(False)
        MainWindow.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.CameraLog = QtWidgets.QTabWidget(self.centralwidget)
        self.CameraLog.setEnabled(True)
        self.CameraLog.setGeometry(QtCore.QRect(0, 0, 1151, 851))
        self.CameraLog.setObjectName("CameraLog")
        self.tab_camera = QtWidgets.QWidget()
        self.tab_camera.setObjectName("tab_camera")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab_camera)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(982, 0, 161, 331))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_error = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_error.setFont(font)
        self.label_error.setObjectName("label_error")
        self.verticalLayout.addWidget(self.label_error)
        self.edit_error = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.edit_error.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.edit_error.setFont(font)
        self.edit_error.setObjectName("edit_error")
        self.verticalLayout.addWidget(self.edit_error)
        self.label_sharp_curve_row = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_sharp_curve_row.setFont(font)
        self.label_sharp_curve_row.setObjectName("label_sharp_curve_row")
        self.verticalLayout.addWidget(self.label_sharp_curve_row)
        self.edit_sharp_curve_row = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.edit_sharp_curve_row.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.edit_sharp_curve_row.setFont(font)
        self.edit_sharp_curve_row.setObjectName("edit_sharp_curve_row")
        self.verticalLayout.addWidget(self.edit_sharp_curve_row)
        self.label_roundabout = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_roundabout.setFont(font)
        self.label_roundabout.setObjectName("label_roundabout")
        self.verticalLayout.addWidget(self.label_roundabout)
        self.edit_flag_roundabout = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.edit_flag_roundabout.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.edit_flag_roundabout.setFont(font)
        self.edit_flag_roundabout.setObjectName("edit_flag_roundabout")
        self.verticalLayout.addWidget(self.edit_flag_roundabout)
        self.label_three_way_fork = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_three_way_fork.setFont(font)
        self.label_three_way_fork.setObjectName("label_three_way_fork")
        self.verticalLayout.addWidget(self.label_three_way_fork)
        self.edit_flag_threeway = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.edit_flag_threeway.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.edit_flag_threeway.setFont(font)
        self.edit_flag_threeway.setObjectName("edit_flag_threeway")
        self.verticalLayout.addWidget(self.edit_flag_threeway)
        self.label_jitter_left = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_jitter_left.setFont(font)
        self.label_jitter_left.setObjectName("label_jitter_left")
        self.verticalLayout.addWidget(self.label_jitter_left)
        self.edit_lane_jitter = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.edit_lane_jitter.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.edit_lane_jitter.setFont(font)
        self.edit_lane_jitter.setObjectName("edit_lane_jitter")
        self.verticalLayout.addWidget(self.edit_lane_jitter)
        self.label_jitter_right_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_jitter_right_2.setFont(font)
        self.label_jitter_right_2.setObjectName("label_jitter_right_2")
        self.verticalLayout.addWidget(self.label_jitter_right_2)
        self.edit_roundaboutarea = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.edit_roundaboutarea.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.edit_roundaboutarea.setFont(font)
        self.edit_roundaboutarea.setObjectName("edit_roundaboutarea")
        self.verticalLayout.addWidget(self.edit_roundaboutarea)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tab_camera)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(980, 580, 160, 238))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_ip_control = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_ip_control.setFont(font)
        self.label_ip_control.setStyleSheet("")
        self.label_ip_control.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ip_control.setObjectName("label_ip_control")
        self.verticalLayout_3.addWidget(self.label_ip_control)
        self.edit_ip_address_control = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.edit_ip_address_control.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.edit_ip_address_control.setFont(font)
        self.edit_ip_address_control.setText("")
        self.edit_ip_address_control.setObjectName("edit_ip_address_control")
        self.verticalLayout_3.addWidget(self.edit_ip_address_control)
        self.button_connect_control = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.button_connect_control.setFont(font)
        self.button_connect_control.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.button_connect_control.setObjectName("button_connect_control")
        self.verticalLayout_3.addWidget(self.button_connect_control)
        self.label_ip_camera = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_ip_camera.setFont(font)
        self.label_ip_camera.setStyleSheet("")
        self.label_ip_camera.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ip_camera.setObjectName("label_ip_camera")
        self.verticalLayout_3.addWidget(self.label_ip_camera)
        self.edit_ip_address_camera = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.edit_ip_address_camera.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.edit_ip_address_camera.setFont(font)
        self.edit_ip_address_camera.setText("")
        self.edit_ip_address_camera.setObjectName("edit_ip_address_camera")
        self.verticalLayout_3.addWidget(self.edit_ip_address_camera)
        self.button_connect_camera = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.button_connect_camera.setFont(font)
        self.button_connect_camera.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.button_connect_camera.setObjectName("button_connect_camera")
        self.verticalLayout_3.addWidget(self.button_connect_camera)
        self.button_get_one = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.button_get_one.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.button_get_one.setFont(font)
        self.button_get_one.setObjectName("button_get_one")
        self.verticalLayout_3.addWidget(self.button_get_one)
        self.button_remote_camera = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.button_remote_camera.setFont(font)
        self.button_remote_camera.setObjectName("button_remote_camera")
        self.verticalLayout_3.addWidget(self.button_remote_camera)
        self.edit_camera = QtWidgets.QTextEdit(self.tab_camera)
        self.edit_camera.setEnabled(False)
        self.edit_camera.setGeometry(QtCore.QRect(0, 0, 811, 821))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.edit_camera.setFont(font)
        self.edit_camera.setObjectName("edit_camera")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_camera)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(990, 485, 141, 89))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_w = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_w.setFont(font)
        self.label_w.setFrameShape(QtWidgets.QFrame.Box)
        self.label_w.setAlignment(QtCore.Qt.AlignCenter)
        self.label_w.setObjectName("label_w")
        self.gridLayout.addWidget(self.label_w, 1, 1, 1, 1)
        self.label_Esc = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_Esc.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_Esc.setFont(font)
        self.label_Esc.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Esc.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Esc.setObjectName("label_Esc")
        self.gridLayout.addWidget(self.label_Esc, 0, 0, 1, 1)
        self.label_S = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_S.setFont(font)
        self.label_S.setFrameShape(QtWidgets.QFrame.Box)
        self.label_S.setAlignment(QtCore.Qt.AlignCenter)
        self.label_S.setObjectName("label_S")
        self.gridLayout.addWidget(self.label_S, 2, 1, 1, 1)
        self.label_k = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_k.setFont(font)
        self.label_k.setFrameShape(QtWidgets.QFrame.Box)
        self.label_k.setAlignment(QtCore.Qt.AlignCenter)
        self.label_k.setObjectName("label_k")
        self.gridLayout.addWidget(self.label_k, 0, 2, 1, 1)
        self.label_A = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_A.setFont(font)
        self.label_A.setFrameShape(QtWidgets.QFrame.Box)
        self.label_A.setAlignment(QtCore.Qt.AlignCenter)
        self.label_A.setObjectName("label_A")
        self.gridLayout.addWidget(self.label_A, 2, 0, 1, 1)
        self.label_Q = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_Q.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_Q.setFont(font)
        self.label_Q.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Q.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Q.setObjectName("label_Q")
        self.gridLayout.addWidget(self.label_Q, 1, 0, 1, 1)
        self.label_D = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_D.setFont(font)
        self.label_D.setFrameShape(QtWidgets.QFrame.Box)
        self.label_D.setAlignment(QtCore.Qt.AlignCenter)
        self.label_D.setObjectName("label_D")
        self.gridLayout.addWidget(self.label_D, 2, 2, 1, 1)
        self.label_f = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_f.setFont(font)
        self.label_f.setFrameShape(QtWidgets.QFrame.Box)
        self.label_f.setAlignment(QtCore.Qt.AlignCenter)
        self.label_f.setObjectName("label_f")
        self.gridLayout.addWidget(self.label_f, 1, 2, 1, 1)
        self.label_f_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_f_2.setFont(font)
        self.label_f_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_f_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_f_2.setObjectName("label_f_2")
        self.gridLayout.addWidget(self.label_f_2, 1, 3, 1, 1)
        self.label_D_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_D_2.setFont(font)
        self.label_D_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_D_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_D_2.setObjectName("label_D_2")
        self.gridLayout.addWidget(self.label_D_2, 2, 3, 1, 1)
        self.edit_log_control = QtWidgets.QTextEdit(self.tab_camera)
        self.edit_log_control.setEnabled(False)
        self.edit_log_control.setGeometry(QtCore.QRect(815, 0, 161, 581))
        self.edit_log_control.setObjectName("edit_log_control")
        self.edit_log_state = QtWidgets.QTextEdit(self.tab_camera)
        self.edit_log_state.setEnabled(False)
        self.edit_log_state.setGeometry(QtCore.QRect(815, 585, 161, 236))
        self.edit_log_state.setObjectName("edit_log_state")
        self.CameraLog.addTab(self.tab_camera, "")
        self.tab_paramerter = QtWidgets.QWidget()
        self.tab_paramerter.setObjectName("tab_paramerter")
        self.edit_log_parameter = QtWidgets.QTextEdit(self.tab_paramerter)
        self.edit_log_parameter.setEnabled(False)
        self.edit_log_parameter.setGeometry(QtCore.QRect(900, 10, 231, 801))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.edit_log_parameter.setFont(font)
        self.edit_log_parameter.setObjectName("edit_log_parameter")
        self.layoutWidget = QtWidgets.QWidget(self.tab_paramerter)
        self.layoutWidget.setGeometry(QtCore.QRect(490, 10, 262, 421))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_10.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_turn_i = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_turn_i.sizePolicy().hasHeightForWidth())
        self.label_turn_i.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_turn_i.setFont(font)
        self.label_turn_i.setFrameShape(QtWidgets.QFrame.Box)
        self.label_turn_i.setAlignment(QtCore.Qt.AlignCenter)
        self.label_turn_i.setObjectName("label_turn_i")
        self.gridLayout_10.addWidget(self.label_turn_i, 14, 1, 1, 1)
        self.button_turnn_d = QtWidgets.QPushButton(self.layoutWidget)
        self.button_turnn_d.setObjectName("button_turnn_d")
        self.gridLayout_10.addWidget(self.button_turnn_d, 15, 3, 1, 1)
        self.edit_speed_i = QtWidgets.QLineEdit(self.layoutWidget)
        self.edit_speed_i.setEnabled(True)
        self.edit_speed_i.setObjectName("edit_speed_i")
        self.gridLayout_10.addWidget(self.edit_speed_i, 6, 2, 1, 1)
        self.label_turn_p = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_turn_p.sizePolicy().hasHeightForWidth())
        self.label_turn_p.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_turn_p.setFont(font)
        self.label_turn_p.setFrameShape(QtWidgets.QFrame.Box)
        self.label_turn_p.setAlignment(QtCore.Qt.AlignCenter)
        self.label_turn_p.setObjectName("label_turn_p")
        self.gridLayout_10.addWidget(self.label_turn_p, 13, 1, 1, 1)
        self.edit_angle_p = QtWidgets.QLineEdit(self.layoutWidget)
        self.edit_angle_p.setEnabled(True)
        self.edit_angle_p.setObjectName("edit_angle_p")
        self.gridLayout_10.addWidget(self.edit_angle_p, 9, 2, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_9.setFont(font)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_10.addWidget(self.label_9, 2, 1, 1, 3)
        self.button_angle_i = QtWidgets.QPushButton(self.layoutWidget)
        self.button_angle_i.setObjectName("button_angle_i")
        self.gridLayout_10.addWidget(self.button_angle_i, 10, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_10.addWidget(self.label_6, 8, 1, 1, 3)
        self.label_turn_p_2 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_turn_p_2.sizePolicy().hasHeightForWidth())
        self.label_turn_p_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_turn_p_2.setFont(font)
        self.label_turn_p_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_turn_p_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_turn_p_2.setObjectName("label_turn_p_2")
        self.gridLayout_10.addWidget(self.label_turn_p_2, 5, 1, 1, 1)
        self.label_turn_d_2 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_turn_d_2.sizePolicy().hasHeightForWidth())
        self.label_turn_d_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_turn_d_2.setFont(font)
        self.label_turn_d_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_turn_d_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_turn_d_2.setObjectName("label_turn_d_2")
        self.gridLayout_10.addWidget(self.label_turn_d_2, 6, 1, 1, 1)
        self.edit_turnn_d = QtWidgets.QLineEdit(self.layoutWidget)
        self.edit_turnn_d.setEnabled(True)
        self.edit_turnn_d.setObjectName("edit_turnn_d")
        self.gridLayout_10.addWidget(self.edit_turnn_d, 15, 2, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_8.setFont(font)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_10.addWidget(self.label_8, 1, 1, 1, 3)
        self.button_angle_d = QtWidgets.QPushButton(self.layoutWidget)
        self.button_angle_d.setObjectName("button_angle_d")
        self.gridLayout_10.addWidget(self.button_angle_d, 11, 3, 1, 1)
        self.button_angle_p = QtWidgets.QPushButton(self.layoutWidget)
        self.button_angle_p.setObjectName("button_angle_p")
        self.gridLayout_10.addWidget(self.button_angle_p, 9, 3, 1, 1)
        self.button_speed_i = QtWidgets.QPushButton(self.layoutWidget)
        self.button_speed_i.setObjectName("button_speed_i")
        self.gridLayout_10.addWidget(self.button_speed_i, 6, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_10.addWidget(self.label_5, 4, 1, 1, 3)
        self.label_turn_p_3 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_turn_p_3.sizePolicy().hasHeightForWidth())
        self.label_turn_p_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_turn_p_3.setFont(font)
        self.label_turn_p_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_turn_p_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_turn_p_3.setObjectName("label_turn_p_3")
        self.gridLayout_10.addWidget(self.label_turn_p_3, 9, 1, 1, 1)
        self.edit_speed_p = QtWidgets.QLineEdit(self.layoutWidget)
        self.edit_speed_p.setEnabled(True)
        self.edit_speed_p.setObjectName("edit_speed_p")
        self.gridLayout_10.addWidget(self.edit_speed_p, 5, 2, 1, 1)
        self.edit_angle_d = QtWidgets.QLineEdit(self.layoutWidget)
        self.edit_angle_d.setEnabled(True)
        self.edit_angle_d.setObjectName("edit_angle_d")
        self.gridLayout_10.addWidget(self.edit_angle_d, 11, 2, 1, 1)
        self.label_turn_d_4 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_turn_d_4.sizePolicy().hasHeightForWidth())
        self.label_turn_d_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_turn_d_4.setFont(font)
        self.label_turn_d_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_turn_d_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_turn_d_4.setObjectName("label_turn_d_4")
        self.gridLayout_10.addWidget(self.label_turn_d_4, 10, 1, 1, 1)
        self.button_speed_d = QtWidgets.QPushButton(self.layoutWidget)
        self.button_speed_d.setObjectName("button_speed_d")
        self.gridLayout_10.addWidget(self.button_speed_d, 7, 3, 1, 1)
        self.edit_speed_d = QtWidgets.QLineEdit(self.layoutWidget)
        self.edit_speed_d.setEnabled(True)
        self.edit_speed_d.setObjectName("edit_speed_d")
        self.gridLayout_10.addWidget(self.edit_speed_d, 7, 2, 1, 1)
        self.label_turn_d = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_turn_d.sizePolicy().hasHeightForWidth())
        self.label_turn_d.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_turn_d.setFont(font)
        self.label_turn_d.setFrameShape(QtWidgets.QFrame.Box)
        self.label_turn_d.setAlignment(QtCore.Qt.AlignCenter)
        self.label_turn_d.setObjectName("label_turn_d")
        self.gridLayout_10.addWidget(self.label_turn_d, 15, 1, 1, 1)
        self.label_turn_d_5 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_turn_d_5.sizePolicy().hasHeightForWidth())
        self.label_turn_d_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_turn_d_5.setFont(font)
        self.label_turn_d_5.setFrameShape(QtWidgets.QFrame.Box)
        self.label_turn_d_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_turn_d_5.setObjectName("label_turn_d_5")
        self.gridLayout_10.addWidget(self.label_turn_d_5, 11, 1, 1, 1)
        self.edit_turnn_p = QtWidgets.QLineEdit(self.layoutWidget)
        self.edit_turnn_p.setEnabled(True)
        self.edit_turnn_p.setObjectName("edit_turnn_p")
        self.gridLayout_10.addWidget(self.edit_turnn_p, 13, 2, 1, 1)
        self.edit_turnn_i = QtWidgets.QLineEdit(self.layoutWidget)
        self.edit_turnn_i.setEnabled(True)
        self.edit_turnn_i.setObjectName("edit_turnn_i")
        self.gridLayout_10.addWidget(self.edit_turnn_i, 14, 2, 1, 1)
        self.label_turn_d_3 = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_turn_d_3.sizePolicy().hasHeightForWidth())
        self.label_turn_d_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_turn_d_3.setFont(font)
        self.label_turn_d_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_turn_d_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_turn_d_3.setObjectName("label_turn_d_3")
        self.gridLayout_10.addWidget(self.label_turn_d_3, 7, 1, 1, 1)
        self.edit_angle_i = QtWidgets.QLineEdit(self.layoutWidget)
        self.edit_angle_i.setEnabled(True)
        self.edit_angle_i.setObjectName("edit_angle_i")
        self.gridLayout_10.addWidget(self.edit_angle_i, 10, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout_10.addWidget(self.label_4, 12, 1, 1, 3)
        self.button_turnn_i = QtWidgets.QPushButton(self.layoutWidget)
        self.button_turnn_i.setObjectName("button_turnn_i")
        self.gridLayout_10.addWidget(self.button_turnn_i, 14, 3, 1, 1)
        self.button_speed_p = QtWidgets.QPushButton(self.layoutWidget)
        self.button_speed_p.setObjectName("button_speed_p")
        self.gridLayout_10.addWidget(self.button_speed_p, 5, 3, 1, 1)
        self.button_turnn_p = QtWidgets.QPushButton(self.layoutWidget)
        self.button_turnn_p.setObjectName("button_turnn_p")
        self.gridLayout_10.addWidget(self.button_turnn_p, 13, 3, 1, 1)
        self.label_car_speed = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_car_speed.sizePolicy().hasHeightForWidth())
        self.label_car_speed.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_car_speed.setFont(font)
        self.label_car_speed.setFrameShape(QtWidgets.QFrame.Box)
        self.label_car_speed.setAlignment(QtCore.Qt.AlignCenter)
        self.label_car_speed.setObjectName("label_car_speed")
        self.gridLayout_10.addWidget(self.label_car_speed, 3, 1, 1, 1)
        self.edit_car_speed = QtWidgets.QLineEdit(self.layoutWidget)
        self.edit_car_speed.setEnabled(True)
        self.edit_car_speed.setObjectName("edit_car_speed")
        self.gridLayout_10.addWidget(self.edit_car_speed, 3, 2, 1, 1)
        self.button_car_speed = QtWidgets.QPushButton(self.layoutWidget)
        self.button_car_speed.setObjectName("button_car_speed")
        self.gridLayout_10.addWidget(self.button_car_speed, 3, 3, 1, 1)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab_paramerter)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(30, 10, 278, 391))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.edit_roundabout_area_thres = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.edit_roundabout_area_thres.setEnabled(True)
        self.edit_roundabout_area_thres.setObjectName("edit_roundabout_area_thres")
        self.gridLayout_3.addWidget(self.edit_roundabout_area_thres, 8, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 1, 0, 1, 3)
        self.button_outbound_thres = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.button_outbound_thres.setEnabled(False)
        self.button_outbound_thres.setObjectName("button_outbound_thres")
        self.gridLayout_3.addWidget(self.button_outbound_thres, 11, 2, 1, 1)
        self.label_lane_distance = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_lane_distance.sizePolicy().hasHeightForWidth())
        self.label_lane_distance.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_lane_distance.setFont(font)
        self.label_lane_distance.setFrameShape(QtWidgets.QFrame.Box)
        self.label_lane_distance.setAlignment(QtCore.Qt.AlignCenter)
        self.label_lane_distance.setObjectName("label_lane_distance")
        self.gridLayout_3.addWidget(self.label_lane_distance, 3, 0, 1, 1)
        self.label_roundabout_jitter_thres_curve = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_roundabout_jitter_thres_curve.sizePolicy().hasHeightForWidth())
        self.label_roundabout_jitter_thres_curve.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_roundabout_jitter_thres_curve.setFont(font)
        self.label_roundabout_jitter_thres_curve.setFrameShape(QtWidgets.QFrame.Box)
        self.label_roundabout_jitter_thres_curve.setAlignment(QtCore.Qt.AlignCenter)
        self.label_roundabout_jitter_thres_curve.setObjectName("label_roundabout_jitter_thres_curve")
        self.gridLayout_3.addWidget(self.label_roundabout_jitter_thres_curve, 4, 0, 1, 1)
        self.edit_lane_distance = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.edit_lane_distance.setEnabled(True)
        self.edit_lane_distance.setObjectName("edit_lane_distance")
        self.gridLayout_3.addWidget(self.edit_lane_distance, 3, 1, 1, 1)
        self.button_lane_distance = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.button_lane_distance.setObjectName("button_lane_distance")
        self.gridLayout_3.addWidget(self.button_lane_distance, 3, 2, 1, 1)
        self.label_sharp_jitter_thres = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_sharp_jitter_thres.sizePolicy().hasHeightForWidth())
        self.label_sharp_jitter_thres.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_sharp_jitter_thres.setFont(font)
        self.label_sharp_jitter_thres.setFrameShape(QtWidgets.QFrame.Box)
        self.label_sharp_jitter_thres.setAlignment(QtCore.Qt.AlignCenter)
        self.label_sharp_jitter_thres.setObjectName("label_sharp_jitter_thres")
        self.gridLayout_3.addWidget(self.label_sharp_jitter_thres, 6, 0, 1, 1)
        self.label_lane_thres = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_lane_thres.sizePolicy().hasHeightForWidth())
        self.label_lane_thres.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_lane_thres.setFont(font)
        self.label_lane_thres.setFrameShape(QtWidgets.QFrame.Box)
        self.label_lane_thres.setAlignment(QtCore.Qt.AlignCenter)
        self.label_lane_thres.setObjectName("label_lane_thres")
        self.gridLayout_3.addWidget(self.label_lane_thres, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_3.setFont(font)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 9, 0, 1, 3)
        self.edit_start_point_thres = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.edit_start_point_thres.setEnabled(True)
        self.edit_start_point_thres.setObjectName("edit_start_point_thres")
        self.gridLayout_3.addWidget(self.edit_start_point_thres, 10, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 7, 0, 1, 3)
        self.button_lane_thres = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.button_lane_thres.setObjectName("button_lane_thres")
        self.gridLayout_3.addWidget(self.button_lane_thres, 2, 2, 1, 1)
        self.edit_sharpjitter_thres = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.edit_sharpjitter_thres.setEnabled(True)
        self.edit_sharpjitter_thres.setObjectName("edit_sharpjitter_thres")
        self.gridLayout_3.addWidget(self.edit_sharpjitter_thres, 6, 1, 1, 1)
        self.button_roundabout_area_thres = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.button_roundabout_area_thres.setObjectName("button_roundabout_area_thres")
        self.gridLayout_3.addWidget(self.button_roundabout_area_thres, 8, 2, 1, 1)
        self.button_start_point_thres = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.button_start_point_thres.setEnabled(False)
        self.button_start_point_thres.setObjectName("button_start_point_thres")
        self.gridLayout_3.addWidget(self.button_start_point_thres, 10, 2, 1, 1)
        self.label_roundabout_jitter_thres_straight = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_roundabout_jitter_thres_straight.sizePolicy().hasHeightForWidth())
        self.label_roundabout_jitter_thres_straight.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_roundabout_jitter_thres_straight.setFont(font)
        self.label_roundabout_jitter_thres_straight.setFrameShape(QtWidgets.QFrame.Box)
        self.label_roundabout_jitter_thres_straight.setAlignment(QtCore.Qt.AlignCenter)
        self.label_roundabout_jitter_thres_straight.setObjectName("label_roundabout_jitter_thres_straight")
        self.gridLayout_3.addWidget(self.label_roundabout_jitter_thres_straight, 5, 0, 1, 1)
        self.edit_lane_thres = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.edit_lane_thres.setEnabled(True)
        self.edit_lane_thres.setObjectName("edit_lane_thres")
        self.gridLayout_3.addWidget(self.edit_lane_thres, 2, 1, 1, 1)
        self.button_roundabout_jitter_thres_curve = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.button_roundabout_jitter_thres_curve.setEnabled(False)
        self.button_roundabout_jitter_thres_curve.setObjectName("button_roundabout_jitter_thres_curve")
        self.gridLayout_3.addWidget(self.button_roundabout_jitter_thres_curve, 4, 2, 1, 1)
        self.button_roundabout_jitter_thres_straight = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.button_roundabout_jitter_thres_straight.setEnabled(False)
        self.button_roundabout_jitter_thres_straight.setObjectName("button_roundabout_jitter_thres_straight")
        self.gridLayout_3.addWidget(self.button_roundabout_jitter_thres_straight, 5, 2, 1, 1)
        self.label_roundabout_jitter_thres_straight_3 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_roundabout_jitter_thres_straight_3.sizePolicy().hasHeightForWidth())
        self.label_roundabout_jitter_thres_straight_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_roundabout_jitter_thres_straight_3.setFont(font)
        self.label_roundabout_jitter_thres_straight_3.setFrameShape(QtWidgets.QFrame.Box)
        self.label_roundabout_jitter_thres_straight_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_roundabout_jitter_thres_straight_3.setObjectName("label_roundabout_jitter_thres_straight_3")
        self.gridLayout_3.addWidget(self.label_roundabout_jitter_thres_straight_3, 10, 0, 1, 1)
        self.label_roundabout_jitter_thres_straight_2 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_roundabout_jitter_thres_straight_2.sizePolicy().hasHeightForWidth())
        self.label_roundabout_jitter_thres_straight_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_roundabout_jitter_thres_straight_2.setFont(font)
        self.label_roundabout_jitter_thres_straight_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_roundabout_jitter_thres_straight_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_roundabout_jitter_thres_straight_2.setObjectName("label_roundabout_jitter_thres_straight_2")
        self.gridLayout_3.addWidget(self.label_roundabout_jitter_thres_straight_2, 8, 0, 1, 1)
        self.button_sharp_jitter_thres = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.button_sharp_jitter_thres.setEnabled(False)
        self.button_sharp_jitter_thres.setObjectName("button_sharp_jitter_thres")
        self.gridLayout_3.addWidget(self.button_sharp_jitter_thres, 6, 2, 1, 1)
        self.edit_roundabout_jitter_thres_straight = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.edit_roundabout_jitter_thres_straight.setEnabled(True)
        self.edit_roundabout_jitter_thres_straight.setObjectName("edit_roundabout_jitter_thres_straight")
        self.gridLayout_3.addWidget(self.edit_roundabout_jitter_thres_straight, 5, 1, 1, 1)
        self.label_roundabout_jitter_thres_straight_4 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_roundabout_jitter_thres_straight_4.sizePolicy().hasHeightForWidth())
        self.label_roundabout_jitter_thres_straight_4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_roundabout_jitter_thres_straight_4.setFont(font)
        self.label_roundabout_jitter_thres_straight_4.setFrameShape(QtWidgets.QFrame.Box)
        self.label_roundabout_jitter_thres_straight_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_roundabout_jitter_thres_straight_4.setObjectName("label_roundabout_jitter_thres_straight_4")
        self.gridLayout_3.addWidget(self.label_roundabout_jitter_thres_straight_4, 11, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_3.addWidget(self.label_7, 0, 0, 1, 3)
        self.label_roundabout_jitter_thres_straight_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_roundabout_jitter_thres_straight_5.sizePolicy().hasHeightForWidth())
        self.label_roundabout_jitter_thres_straight_5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_roundabout_jitter_thres_straight_5.setFont(font)
        self.label_roundabout_jitter_thres_straight_5.setFrameShape(QtWidgets.QFrame.Box)
        self.label_roundabout_jitter_thres_straight_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_roundabout_jitter_thres_straight_5.setObjectName("label_roundabout_jitter_thres_straight_5")
        self.gridLayout_3.addWidget(self.label_roundabout_jitter_thres_straight_5, 12, 0, 1, 1)
        self.edit_outbound_thres = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.edit_outbound_thres.setEnabled(True)
        self.edit_outbound_thres.setObjectName("edit_outbound_thres")
        self.gridLayout_3.addWidget(self.edit_outbound_thres, 11, 1, 1, 1)
        self.edit_roundabout_jitter_thres_curve = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.edit_roundabout_jitter_thres_curve.setEnabled(True)
        self.edit_roundabout_jitter_thres_curve.setObjectName("edit_roundabout_jitter_thres_curve")
        self.gridLayout_3.addWidget(self.edit_roundabout_jitter_thres_curve, 4, 1, 1, 1)
        self.edit_slope_row = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.edit_slope_row.setEnabled(True)
        self.edit_slope_row.setObjectName("edit_slope_row")
        self.gridLayout_3.addWidget(self.edit_slope_row, 12, 1, 1, 1)
        self.button_outbound_thres_2 = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.button_outbound_thres_2.setEnabled(True)
        self.button_outbound_thres_2.setObjectName("button_outbound_thres_2")
        self.gridLayout_3.addWidget(self.button_outbound_thres_2, 12, 2, 1, 1)
        self.CameraLog.addTab(self.tab_paramerter, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.textEdit = QtWidgets.QTextEdit(self.tab)
        self.textEdit.setGeometry(QtCore.QRect(30, 120, 1071, 691))
        self.textEdit.setObjectName("textEdit")
        self.button_lane_thres_2 = QtWidgets.QPushButton(self.tab)
        self.button_lane_thres_2.setGeometry(QtCore.QRect(370, 70, 78, 23))
        self.button_lane_thres_2.setObjectName("button_lane_thres_2")
        self.button_lane_thres_3 = QtWidgets.QPushButton(self.tab)
        self.button_lane_thres_3.setGeometry(QtCore.QRect(550, 70, 78, 23))
        self.button_lane_thres_3.setObjectName("button_lane_thres_3")
        self.CameraLog.addTab(self.tab, "")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.CameraLog.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Smart Car Camera Viewer"))
        self.label_error.setText(_translate("MainWindow", "Error:"))
        self.label_sharp_curve_row.setText(_translate("MainWindow", "Sharp Curve Row:"))
        self.label_roundabout.setText(_translate("MainWindow", "FlagRoundabout:"))
        self.label_three_way_fork.setText(_translate("MainWindow", "FlagEnterThreeway"))
        self.label_jitter_left.setText(_translate("MainWindow", "laneJitter(L, R)"))
        self.label_jitter_right_2.setText(_translate("MainWindow", "roundaboutArea(L, R)"))
        self.label_ip_control.setText(_translate("MainWindow", "Control Core (IP:Port)"))
        self.button_connect_control.setText(_translate("MainWindow", "Connect"))
        self.label_ip_camera.setText(_translate("MainWindow", "Camera Core (IP:Port)"))
        self.button_connect_camera.setText(_translate("MainWindow", "Connect"))
        self.button_get_one.setText(_translate("MainWindow", "Get One Frame (Q)"))
        self.button_remote_camera.setText(_translate("MainWindow", "Remote Camera"))
        self.edit_camera.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\';\"><br /></p></body></html>"))
        self.label_w.setText(_translate("MainWindow", "W"))
        self.label_Esc.setText(_translate("MainWindow", "Esc"))
        self.label_S.setText(_translate("MainWindow", "S"))
        self.label_k.setText(_translate("MainWindow", "K"))
        self.label_A.setText(_translate("MainWindow", "A"))
        self.label_Q.setText(_translate("MainWindow", "Q"))
        self.label_D.setText(_translate("MainWindow", "D"))
        self.label_f.setText(_translate("MainWindow", "F"))
        self.label_f_2.setText(_translate("MainWindow", "T"))
        self.label_D_2.setText(_translate("MainWindow", "G"))
        self.CameraLog.setTabText(self.CameraLog.indexOf(self.tab_camera), _translate("MainWindow", "Camera"))
        self.label_turn_i.setText(_translate("MainWindow", "turn_ki"))
        self.button_turnn_d.setText(_translate("MainWindow", "Change"))
        self.edit_speed_i.setText(_translate("MainWindow", "0.2"))
        self.label_turn_p.setText(_translate("MainWindow", "turn_kp"))
        self.edit_angle_p.setText(_translate("MainWindow", "0.5"))
        self.label_9.setText(_translate("MainWindow", "Run"))
        self.button_angle_i.setText(_translate("MainWindow", "Change"))
        self.label_6.setText(_translate("MainWindow", "Angle Loop"))
        self.label_turn_p_2.setText(_translate("MainWindow", "speed_kp"))
        self.label_turn_d_2.setText(_translate("MainWindow", "speed_ki"))
        self.edit_turnn_d.setText(_translate("MainWindow", "0.2"))
        self.label_8.setText(_translate("MainWindow", "Control"))
        self.button_angle_d.setText(_translate("MainWindow", "Change"))
        self.button_angle_p.setText(_translate("MainWindow", "Change"))
        self.button_speed_i.setText(_translate("MainWindow", "Change"))
        self.label_5.setText(_translate("MainWindow", "Speed Loop"))
        self.label_turn_p_3.setText(_translate("MainWindow", "angle_kp"))
        self.edit_speed_p.setText(_translate("MainWindow", "123"))
        self.edit_angle_d.setText(_translate("MainWindow", "0.2"))
        self.label_turn_d_4.setText(_translate("MainWindow", "angle_ki"))
        self.button_speed_d.setText(_translate("MainWindow", "Change"))
        self.edit_speed_d.setText(_translate("MainWindow", "0.2"))
        self.label_turn_d.setText(_translate("MainWindow", "turn_kd"))
        self.label_turn_d_5.setText(_translate("MainWindow", "angle_kd"))
        self.edit_turnn_p.setText(_translate("MainWindow", "0.5"))
        self.edit_turnn_i.setText(_translate("MainWindow", "0.2"))
        self.label_turn_d_3.setText(_translate("MainWindow", "speed_kd"))
        self.edit_angle_i.setText(_translate("MainWindow", "0.2"))
        self.label_4.setText(_translate("MainWindow", "Turning Loop"))
        self.button_turnn_i.setText(_translate("MainWindow", "Change"))
        self.button_speed_p.setText(_translate("MainWindow", "Change"))
        self.button_turnn_p.setText(_translate("MainWindow", "Change"))
        self.label_car_speed.setText(_translate("MainWindow", "car_speed"))
        self.edit_car_speed.setText(_translate("MainWindow", "30"))
        self.button_car_speed.setText(_translate("MainWindow", "Change"))
        self.edit_roundabout_area_thres.setText(_translate("MainWindow", "500"))
        self.label.setText(_translate("MainWindow", "Lane"))
        self.button_outbound_thres.setText(_translate("MainWindow", "Change"))
        self.label_lane_distance.setText(_translate("MainWindow", "lane_distance"))
        self.label_roundabout_jitter_thres_curve.setText(_translate("MainWindow", "rouJitThrCur"))
        self.edit_lane_distance.setText(_translate("MainWindow", "1.7"))
        self.button_lane_distance.setText(_translate("MainWindow", "Change"))
        self.label_sharp_jitter_thres.setText(_translate("MainWindow", "sharpJitThr"))
        self.label_lane_thres.setText(_translate("MainWindow", "lane_thres"))
        self.label_3.setText(_translate("MainWindow", "Others"))
        self.edit_start_point_thres.setText(_translate("MainWindow", "50"))
        self.label_2.setText(_translate("MainWindow", "Roundabout"))
        self.button_lane_thres.setText(_translate("MainWindow", "Change"))
        self.edit_sharpjitter_thres.setText(_translate("MainWindow", "15"))
        self.button_roundabout_area_thres.setText(_translate("MainWindow", "Change"))
        self.button_start_point_thres.setText(_translate("MainWindow", "Change"))
        self.label_roundabout_jitter_thres_straight.setText(_translate("MainWindow", "rouJitThrStr"))
        self.edit_lane_thres.setText(_translate("MainWindow", "110"))
        self.button_roundabout_jitter_thres_curve.setText(_translate("MainWindow", "Change"))
        self.button_roundabout_jitter_thres_straight.setText(_translate("MainWindow", "Change"))
        self.label_roundabout_jitter_thres_straight_3.setText(_translate("MainWindow", "startPointThres"))
        self.label_roundabout_jitter_thres_straight_2.setText(_translate("MainWindow", "areaThres"))
        self.button_sharp_jitter_thres.setText(_translate("MainWindow", "Change"))
        self.edit_roundabout_jitter_thres_straight.setText(_translate("MainWindow", "3"))
        self.label_roundabout_jitter_thres_straight_4.setText(_translate("MainWindow", "outboundThres"))
        self.label_7.setText(_translate("MainWindow", "Camera"))
        self.label_roundabout_jitter_thres_straight_5.setText(_translate("MainWindow", "slopeRow"))
        self.edit_outbound_thres.setText(_translate("MainWindow", "13000"))
        self.edit_roundabout_jitter_thres_curve.setText(_translate("MainWindow", "-15"))
        self.edit_slope_row.setText(_translate("MainWindow", "43-38"))
        self.button_outbound_thres_2.setText(_translate("MainWindow", "Change"))
        self.CameraLog.setTabText(self.CameraLog.indexOf(self.tab_paramerter), _translate("MainWindow", "Parameter"))
        self.button_lane_thres_2.setText(_translate("MainWindow", "ON"))
        self.button_lane_thres_3.setText(_translate("MainWindow", "OFF"))
        self.CameraLog.setTabText(self.CameraLog.indexOf(self.tab), _translate("MainWindow", "CameraLog"))

