# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1160, 880)
        MainWindow.setMouseTracking(False)
        MainWindow.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1151, 851))
        self.tabWidget.setObjectName("tabWidget")
        self.tab_camera = QtWidgets.QWidget()
        self.tab_camera.setObjectName("tab_camera")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.tab_camera)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(980, 0, 160, 320))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_error = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_error.setFont(font)
        self.label_error.setObjectName("label_error")
        self.verticalLayout.addWidget(self.label_error)
        self.edit_error = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.edit_error.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.edit_error.setFont(font)
        self.edit_error.setObjectName("edit_error")
        self.verticalLayout.addWidget(self.edit_error)
        self.label_slope = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_slope.setFont(font)
        self.label_slope.setObjectName("label_slope")
        self.verticalLayout.addWidget(self.label_slope)
        self.edit_slope = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.edit_slope.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.edit_slope.setFont(font)
        self.edit_slope.setObjectName("edit_slope")
        self.verticalLayout.addWidget(self.edit_slope)
        self.label_sharp_curve_row = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_sharp_curve_row.setFont(font)
        self.label_sharp_curve_row.setObjectName("label_sharp_curve_row")
        self.verticalLayout.addWidget(self.label_sharp_curve_row)
        self.edit_sharp_curve_row = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.edit_sharp_curve_row.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.edit_sharp_curve_row.setFont(font)
        self.edit_sharp_curve_row.setObjectName("edit_sharp_curve_row")
        self.verticalLayout.addWidget(self.edit_sharp_curve_row)
        self.label_miss_count = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_miss_count.setFont(font)
        self.label_miss_count.setObjectName("label_miss_count")
        self.verticalLayout.addWidget(self.label_miss_count)
        self.edit_miss_count = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.edit_miss_count.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.edit_miss_count.setFont(font)
        self.edit_miss_count.setObjectName("edit_miss_count")
        self.verticalLayout.addWidget(self.edit_miss_count)
        self.label_roundabout = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_roundabout.setFont(font)
        self.label_roundabout.setObjectName("label_roundabout")
        self.verticalLayout.addWidget(self.label_roundabout)
        self.edit_roundabout = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.edit_roundabout.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.edit_roundabout.setFont(font)
        self.edit_roundabout.setObjectName("edit_roundabout")
        self.verticalLayout.addWidget(self.edit_roundabout)
        self.label_three_way_fork = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_three_way_fork.setFont(font)
        self.label_three_way_fork.setObjectName("label_three_way_fork")
        self.verticalLayout.addWidget(self.label_three_way_fork)
        self.edit_three_way_fork = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.edit_three_way_fork.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.edit_three_way_fork.setFont(font)
        self.edit_three_way_fork.setObjectName("edit_three_way_fork")
        self.verticalLayout.addWidget(self.edit_three_way_fork)
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.tab_camera)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(980, 650, 160, 170))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_port = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_port.setFont(font)
        self.label_port.setStyleSheet("")
        self.label_port.setAlignment(QtCore.Qt.AlignCenter)
        self.label_port.setObjectName("label_port")
        self.verticalLayout_3.addWidget(self.label_port)
        self.edit_port = QtWidgets.QLineEdit(self.verticalLayoutWidget_3)
        self.edit_port.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.edit_port.setFont(font)
        self.edit_port.setObjectName("edit_port")
        self.verticalLayout_3.addWidget(self.edit_port)
        self.button_serial = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.button_serial.setFont(font)
        self.button_serial.setObjectName("button_serial")
        self.verticalLayout_3.addWidget(self.button_serial)
        self.button_get_one = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.button_get_one.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.button_get_one.setFont(font)
        self.button_get_one.setObjectName("button_get_one")
        self.verticalLayout_3.addWidget(self.button_get_one)
        self.button_get_in_realtime = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.button_get_in_realtime.setFont(font)
        self.button_get_in_realtime.setObjectName("button_get_in_realtime")
        self.verticalLayout_3.addWidget(self.button_get_in_realtime)
        self.label_time = QtWidgets.QLabel(self.verticalLayoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_time.setFont(font)
        self.label_time.setStyleSheet("")
        self.label_time.setAlignment(QtCore.Qt.AlignCenter)
        self.label_time.setObjectName("label_time")
        self.verticalLayout_3.addWidget(self.label_time)
        self.edit_camera = QtWidgets.QTextEdit(self.tab_camera)
        self.edit_camera.setEnabled(True)
        self.edit_camera.setGeometry(QtCore.QRect(0, 0, 971, 821))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.edit_camera.setFont(font)
        self.edit_camera.setObjectName("edit_camera")
        self.gridLayoutWidget = QtWidgets.QWidget(self.tab_camera)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(980, 440, 160, 131))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_Q = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_Q.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_Q.setFont(font)
        self.label_Q.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Q.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Q.setObjectName("label_Q")
        self.gridLayout.addWidget(self.label_Q, 1, 0, 1, 1)
        self.label_S = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_S.setFont(font)
        self.label_S.setFrameShape(QtWidgets.QFrame.Box)
        self.label_S.setAlignment(QtCore.Qt.AlignCenter)
        self.label_S.setObjectName("label_S")
        self.gridLayout.addWidget(self.label_S, 2, 1, 1, 1)
        self.label_D = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_D.setFont(font)
        self.label_D.setFrameShape(QtWidgets.QFrame.Box)
        self.label_D.setAlignment(QtCore.Qt.AlignCenter)
        self.label_D.setObjectName("label_D")
        self.gridLayout.addWidget(self.label_D, 2, 2, 1, 1)
        self.label_w = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_w.setFont(font)
        self.label_w.setFrameShape(QtWidgets.QFrame.Box)
        self.label_w.setAlignment(QtCore.Qt.AlignCenter)
        self.label_w.setObjectName("label_w")
        self.gridLayout.addWidget(self.label_w, 1, 1, 1, 1)
        self.label_E = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_E.setFont(font)
        self.label_E.setFrameShape(QtWidgets.QFrame.Box)
        self.label_E.setAlignment(QtCore.Qt.AlignCenter)
        self.label_E.setObjectName("label_E")
        self.gridLayout.addWidget(self.label_E, 1, 2, 1, 1)
        self.label_A = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_A.setFont(font)
        self.label_A.setFrameShape(QtWidgets.QFrame.Box)
        self.label_A.setAlignment(QtCore.Qt.AlignCenter)
        self.label_A.setObjectName("label_A")
        self.gridLayout.addWidget(self.label_A, 2, 0, 1, 1)
        self.label_Esc = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_Esc.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_Esc.setFont(font)
        self.label_Esc.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Esc.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Esc.setObjectName("label_Esc")
        self.gridLayout.addWidget(self.label_Esc, 0, 0, 1, 1)
        self.label_Space = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_Space.setFont(font)
        self.label_Space.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Space.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Space.setObjectName("label_Space")
        self.gridLayout.addWidget(self.label_Space, 3, 0, 1, 3)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 2)
        self.tabWidget.addTab(self.tab_camera, "")
        self.tab_paramerter = QtWidgets.QWidget()
        self.tab_paramerter.setObjectName("tab_paramerter")
        self.tableWidget = QtWidgets.QTableWidget(self.tab_paramerter)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 500, 600))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(250)
        self.tableWidget.horizontalHeader().setSortIndicatorShown(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab_paramerter)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(520, 10, 160, 136))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_name = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_name.setFont(font)
        self.label_name.setObjectName("label_name")
        self.verticalLayout_2.addWidget(self.label_name)
        self.edit_name = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.edit_name.setFont(font)
        self.edit_name.setObjectName("edit_name")
        self.verticalLayout_2.addWidget(self.edit_name)
        self.label_value = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_value.setFont(font)
        self.label_value.setObjectName("label_value")
        self.verticalLayout_2.addWidget(self.label_value)
        self.edit_value = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.edit_value.setFont(font)
        self.edit_value.setObjectName("edit_value")
        self.verticalLayout_2.addWidget(self.edit_value)
        self.button_sync = QtWidgets.QPushButton(self.verticalLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.button_sync.setFont(font)
        self.button_sync.setObjectName("button_sync")
        self.verticalLayout_2.addWidget(self.button_sync)
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.tab_paramerter)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(520, 230, 196, 80))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.button_thres_up = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.button_thres_up.setFont(font)
        self.button_thres_up.setObjectName("button_thres_up")
        self.gridLayout_2.addWidget(self.button_thres_up, 0, 0, 1, 1)
        self.button_thres_down = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.button_thres_down.setFont(font)
        self.button_thres_down.setObjectName("button_thres_down")
        self.gridLayout_2.addWidget(self.button_thres_down, 0, 1, 1, 1)
        self.button_distance_up = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.button_distance_up.setFont(font)
        self.button_distance_up.setObjectName("button_distance_up")
        self.gridLayout_2.addWidget(self.button_distance_up, 1, 0, 1, 1)
        self.button_distance_down = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.button_distance_down.setFont(font)
        self.button_distance_down.setObjectName("button_distance_down")
        self.gridLayout_2.addWidget(self.button_distance_down, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_paramerter, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Smart Car Camera Viewer"))
        self.label_error.setText(_translate("MainWindow", "Error:"))
        self.label_slope.setText(_translate("MainWindow", "slope:"))
        self.label_sharp_curve_row.setText(_translate("MainWindow", "Sharp Curve Row:"))
        self.label_miss_count.setText(_translate("MainWindow", "Miss Count:"))
        self.label_roundabout.setText(_translate("MainWindow", "FlagRoundabout:"))
        self.label_three_way_fork.setText(_translate("MainWindow", "FlagThreeWayFork:"))
        self.label_port.setText(_translate("MainWindow", "Com Port:"))
        self.edit_port.setText(_translate("MainWindow", "COM"))
        self.button_serial.setText(_translate("MainWindow", "Open Serial"))
        self.button_get_one.setText(_translate("MainWindow", "Get One Frame (Q)"))
        self.button_get_in_realtime.setText(_translate("MainWindow", "Get In Realtime (E)"))
        self.label_time.setText(_translate("MainWindow", "Current Time"))
        self.edit_camera.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p></body></html>"))
        self.label_Q.setText(_translate("MainWindow", "Q"))
        self.label_S.setText(_translate("MainWindow", "S"))
        self.label_D.setText(_translate("MainWindow", "D"))
        self.label_w.setText(_translate("MainWindow", "W"))
        self.label_E.setText(_translate("MainWindow", "E"))
        self.label_A.setText(_translate("MainWindow", "A"))
        self.label_Esc.setText(_translate("MainWindow", "Esc"))
        self.label_Space.setText(_translate("MainWindow", "Space"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_camera), _translate("MainWindow", "Camera"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Value"))
        self.label_name.setText(_translate("MainWindow", "Name:"))
        self.label_value.setText(_translate("MainWindow", "Value:"))
        self.button_sync.setText(_translate("MainWindow", "sync"))
        self.button_thres_up.setText(_translate("MainWindow", "thres_up"))
        self.button_thres_down.setText(_translate("MainWindow", "thres_down"))
        self.button_distance_up.setText(_translate("MainWindow", "distance_up"))
        self.button_distance_down.setText(_translate("MainWindow", "distance_down"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_paramerter), _translate("MainWindow", "Parameter"))

